version: "3.2"
services:
  server7:
    image: rabbitmq:3.10.9-management
    hostname: server7
    container_name: 'server7'
    ports:
    - "5677:5677"
    - "15677:15677"
    - "5557:5557"
    - "15697:15697"
    volumes:
#     - ./advanced.config:/etc/rabbitmq/advanced.config
    - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    - ./mnesia:/var/lib/rabbitmq/mnesia/rabbit@server7
    - type: bind
      source: $PWD/advanced.config
      target: /etc/rabbitmq/advanced.config
    - type: bind
      source: $PWD/.bash_history
      target: /var/lib/rabbitmq/.bash_history
    - type: bind
      source: $PWD/.erlang.cookie
      target: /var/lib/rabbitmq/.erlang.cookie
    networks:
    - rabbitmq_s_net
    - rabbitmq_p_net
    environment:
    - RABBITMQ_DEFAULT_USER=rabbit_admin
    - RABBITMQ_DEFAULT_PASS=.123-321.
    - RABBITMQ_CONFIG_FILES=/etc/rabbitmq/rabbitmq.conf
    - RABBITMQ_ADVANCED_CONFIG_FILE=/etc/rabbitmq/advanced.config
    - RABBITMQ_NODENAME=rabbit@server7
    - RABBITMQ_NODE_PORT=5677
    
networks:
  rabbitmq_s_net:
    external: true
    name: sales_net
  rabbitmq_p_net:
    external: true
    name: purchase_net